### ISSUE TITLE
Pre-requisites: Cloudshell in the AWS console.

### ISSUE THREAD

**Issue by SalmanAbdulrazaq** [aws-deepracer-community/deepracer-genai-workshop#6]
1 major things that shows the error is **Clone successful, but checkout failed**, when I want to git add, It's not working as expected 
in **consequence** when I run `./initial-workshop-setup.sh <aws_bucket_name_to_create> `_it appears command not found

Full Picture implementation in Cloudsheel:
`run git clone https://github.com/aws-deepracer-community/deepracer-genai-workshop.git`
`run cd deepracer-genai-workshop`
`run ./initial-workshop-setup.sh <aws_bucket_name_to_create>`
<img width="1152" alt="Screenshot " src="https://github.com/aws-deepracer-community/deepracer-genai-workshop/assets/126229894/fa052552-43e5-4a5b-8256-dec9e8796719">

Running this code in Cloudshell:` run git clone https://github.com/aws-deepracer-community/deepracer-genai-workshop.git`
it pops out **Clone successful, but checkout failed, below pic**
<img width="1123" alt="Screenshot cloning" src="https://github.com/aws-deepracer-community/deepracer-genai-workshop/assets/126229894/23b56188-48b6-45b6-915b-e50530dc4917">

I wrote `git status` to **see the checkout failed**, when _I git add them this was it appers to me._ 
<img width="971" alt="Git status" src="https://github.com/aws-deepracer-community/deepracer-genai-workshop/assets/126229894/95488c08-d8a7-4401-9311-ecbe65272e93">
*List directories:* 
<img width="654" alt="Screenshot Directories" src="https://github.com/aws-deepracer-community/deepracer-genai-workshop/assets/126229894/36435c1a-015d-4e08-9632-0ca93409d0bf">
When I run this code `run ./initial-workshop-setup.sh <aws_bucket_name_to_create>` this appears to me, I even tried without bucket name just to see the result. 
<img width="971" alt="init" src="https://github.com/aws-deepracer-community/deepracer-genai-workshop/assets/126229894/bcc4b00b-fbca-4fdc-9695-699e934ac681">

**Comment by MarkitectRoss** [comment]
try pulling down the cloud-shell-init branch only (syntax can be seen here https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-git-clone-a-specific-branch-only), the issue is the repo is large and cloudshell has limited storage

Alternative is to use your own IDE

**Comment by MarkitectRoss** [comment]
Readme updated to reflect for to initiate with cloudshell.
